---
- name: Install and Start Apache
  hosts: all
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
        
    - name: correct index.html is present
      copy:
        src: /home/navila/files/index.html
        dest: /var/www/html/index.html
